### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by pascal20997** [jweiland-net/service_bw2#59]
- [ ] Add frontend screenshots
- [ ] Update extension manager configuration part for TYPO3 >= 10
- [ ] Update user manual and add new filter options oft Services list

**Comment by sfroemkenjw** [comment]
Hello @pascal20997 

that you for your issue. As I only have one account the frontend images would show original records from that customer. It's up to the customer to decide, if these records are available for frontend or not. So, I will not add images from frontend.

The third option with "filter options of Services list" I don't understand.

So, currently I will update the documentation for your second option.

Stefan

**Comment by sfroemkenjw** [comment]
Hello @pascal20997 

I hope that's OK for you:
https://docs.typo3.org/p/jweiland/service-bw2/6.0/en-us/Installation/Index.html
https://docs.typo3.org/p/jweiland/service-bw2/6.0/en-us/Configuration/TypoScript/Index.html

Have a cool start into this new week

Stefan
