### ISSUE TITLE
alphabetical index missing?

### ISSUE THREAD

**Issue by the-andyman** [jweiland-net/service_bw2#66]
In an older TYPO3 project i used service_bw2 version 3.0.2 with an alphabetical index (a-z list) and grouping in the list view of "Lebenslagen" and "Leistungen". 
Is this still included in version 5.0.4? Because I can't find the necessary partial template.

**Comment by froemken** [comment]
Hello @the-andyman 

you're right, the index was removed with update to 5.0.0. I have checked GIT history and I saw that a widget was removed. Widgets are deprecated with TYPO3 10 and removed with TYPO3 11. Maybe that's the reason why my colleague has removed that part.

Have a nice start into this weekend.

Stefan

**Comment by sfroemkenjw** [comment]
Hello @the-andyman 

I just tried to add the A-Z list, but Lebenslagen is a tree and not just an UL/LI list. Maybe that's the reason why my colleague has removed that glossar from template.
I close this issue for now. If you have further information for me please feel free to re-open that issue.

Stefan
