### ISSUE TITLE
Exception, while deactivating another extension

### ISSUE THREAD

**Issue by froemken** [jweiland-net/service_bw2#68]
Hi,

while deactivating another extension the ExtensionManagementUtility::isLoaded throws an Exception because of undefined self::$packageManager.

Maybe use the $container->get(PackageManager::class) to initialize EMU correctly.

Stefan

**Comment by sfroemkenjw** [comment]
I can not find any EMU::isLoaded calls in ext_localcon and other TCA files anymore. I think this problem is solved in the meanwhile.
